server:
  port: 8082
  
spring:
  
  application:
    name: HOTEL-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 123456789
 # config:
#    import: configserver:http://localhost:8085  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #properties:
      
#    it will take the dialect automatically

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka