server:
  port: 8081
  
spring:

  config:
    import: configserver:http://localhost:8085
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 123456789
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE    #properties:

     

#    it will take the dialect automatically

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka     
#  instance:
#    prefer-ip-address: true
    
                  #configuration for actuators
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
  endpoint:
    health:
      show-details: always

                                   #configuration of resiliance4j circuitbreaker

resilience4j:
  circuitbreaker:
    instances:
      breakerRatingHotel:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
        
        
#  retry:
#    instances:
#      breakerRatinngHotel:
#        max-attempts: 5
#        wait-duration: 2s
#  
#  ratelimiter:
#    instances:
#      breakerRatinngHotel:
#        limit-refresh-period: 4s
#        limit-for-period: 2
#        timeout-duration: 0s
        
        





    
    
    