server:
  port: 8083



  
spring:
  application:
    name: RATING-SERVICE
  config:
    import: configserver:http://localhost:8085
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 123456789
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #properties:
     
#    it will take the dialect automatically
#eureka:
#  instance:
#    prefer-ip-address: true
#    
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka  